name: preorderpadi
description: "a preorder ecommerce application for everyone."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

#------------------ PACKAGES ------------------------#
dependencies:
  flutter:
    sdk: flutter

#------------------------Utility Packages --------------------#

#------------------icons -------------------------#
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

#---------- State Management ------------#

#-------- Product Specific ----------------------#



#-------------------------- ./ PACKAGES END ---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

#---------- Local Assets folder ----------------#
  assets:
     - assets/
     - assets/fonts/
     - assets/icons/
     - assets/images/
     - assets/logos/

#-------------- Local fonts folder ----------------#
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Thin.ttf
         weight: 100
       - asset: assets/fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700
       - asset: assets/fonts/Poppins-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Poppins-Black.ttf
         weight: 900
       - asset: assets/fonts/Poppins-BlackItalic.ttf
         weight: 900
         style: italic