name: preorderpadi
description: "a preorder ecommerce application for everyone."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

#------------------ PACKAGES ------------------------#
dependencies:
  flutter:
    sdk: flutter

#------------------------Utility Packages --------------------#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.6
#------------------icons -------------------------#
  cupertino_icons: ^1.0.6

  #---------- State Management ------------#
  get: ^4.6.6
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  firebase_core: ^2.25.4
  lottie: ^3.1.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4


#-------- Product Specific ----------------------#



#-------------------------- ./ PACKAGES END ---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

#---------- Local Assets folder ----------------#
  assets:
     - assets/
     - assets/fonts/
     - assets/icons/
     - assets/icons/brands/
     - assets/icons/categories/
     - assets/icons/payment_methods/
     - assets/images/
     - assets/images/animations/
     - assets/images/banners/
     - assets/images/content/
     - assets/images/on_boarding_images/
     - assets/images/products/
     - assets/images/reviews/
     - assets/logos/

#-------------- Local fonts folder ----------------#
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Thin.ttf
         weight: 100
       - asset: assets/fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Poppins-Light.ttf
         weight: 300
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 400
       - asset: assets/fonts/Poppins-Medium.ttf
         weight: 500
       - asset: assets/fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/Poppins-Bold.ttf
         weight: 700
       - asset: assets/fonts/Poppins-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Poppins-Black.ttf
         weight: 900
       - asset: assets/fonts/Poppins-BlackItalic.ttf
         weight: 900
         style: italic