// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKzwHCA9Mmko3UQAV1_CaTh-B_WkjDCkI',
    appId: '1:668687715379:android:c0724fdef70e3003ce2746',
    messagingSenderId: '668687715379',
    projectId: 'preorderpadi-e9166',
    storageBucket: 'preorderpadi-e9166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBN_sfpFA_Iv8HHGCq3WGrDxnxbFaiDs',
    appId: '1:668687715379:ios:e8a8817f4497cc88ce2746',
    messagingSenderId: '668687715379',
    projectId: 'preorderpadi-e9166',
    storageBucket: 'preorderpadi-e9166.appspot.com',
    androidClientId: '668687715379-a612edi3bg5s02o4k12ou7jaaqib1p0a.apps.googleusercontent.com',
    iosClientId: '668687715379-tkfqs43pl5h038hiqpeqd7227tje5pek.apps.googleusercontent.com',
    iosBundleId: 'com.example.preorderpadi',
  );
}
